"""empty message

Revision ID: dcd343c6209b
Revises: 
Create Date: 2021-07-01 20:06:10.610484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd343c6209b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Capitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capital'),
    sa.UniqueConstraint('country')
    )
    op.create_table('CityTemperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('fetch_time', sa.Integer(), nullable=False),
    sa.Column('diff_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CityTemperature')
    op.drop_table('Capitals')
    # ### end Alembic commands ###
